name: Dune Daily Godmode

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت 00:00 UTC اجرا میشه
  workflow_dispatch:     # اجازه اجرای دستی

jobs:
  run_dune_query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Dune Query
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: python run_dune.py

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add dune_output_$(date +'%Y-%m-%d').json
          git commit -m "Update daily Dune output" || echo "No changes"
          git push https://$GH_PAT@github.com/AliLuckyyy/dune-godmode-og.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
